namespace LiveSplit.SonicASRT
{
    enum Tracks : uint
    {
        OceanView = 0xD4257EBD,
        SambaStudios = 0x32D305A8,
        CarrierZone = 0xC72B3B98,
        DragonCanyon = 0x03EB7FFF,
        TempleTrouble = 0xE3121777,
        GalacticParade = 0x4E015AB6,
        SeasonalShrines = 0x503C1CBC,
        RoguesLanding = 0x7534B7CA,
        DreamValley = 0x38A394ED,
        ChillyCastle = 0xC5C9DEA1,
        GraffitiCity = 0xD936550C,
        SanctuaryFalls = 0x4A0FF7AE,
        GraveyardGig = 0xCD8017BA,
        AddersLair = 0xDC93F18B,
        BurningDepths = 0x2DB91FC2,
        RaceOfAges = 0x94610644,
        SunshineTour = 0xE6CD97F0,
        ShibuyaDowntown = 0xE87FDF22,
        RouletteRoad = 0x17463C8D,
        EggHangar = 0xFEBC639E,
        OutrunBay = 0x1EF56CE1
    }

    enum GameMode : byte
    {
        WorldTour = 0,
        GrandPrix = 1,
        TimeAttack = 2,
        SingleRace = 3
    }

    enum WorldTourTrack
    {
        CoastalCruise,
        StudioScrapes,
        BattlezoneBlast,
        DowntownDrift,
        MonkeyMayhem,
        StarrySpeedway,
        RouletteRush,
        CanyonCarnage,
        SnowballShakedown,
        BananaBoost,
        ShinobiScramble,
        SeasideScrap,
        TrickyTraffic,
        StudioScurry,
        GraffitiGroove,
        ShakingSkies,
        NeonKnockout,
        PiratePlunder,
        AdderAssault,
        DreamyDrive,
        SanctuarySpeedway,
        KeilsCarnage,
        CarrierCrisis,
        SunshineSlide,
        RogueRings,
        SeasideSkirmish,
        ShrineTime,
        HangarHassle,
        BootyBoost,
        RacingRangers,
        ShinobiShowdown,
        RuinRun,
        MonkeyBrawl,
        CrumblingChaos,
        HatcherHustle,
        DeathEggDuel,
        UndertakerOvertaker,
        GoldenGauntlet,
        CarnivalClash,
        CurienCurves,
        MoltenMayhem,
        SpeedingSeasons,
        BurningBoost,
        OceanOutrun,
        BillyBackslide,
        CarrierCharge,
        JetSetJaunt,
        ArcadeAnnihilation,
        RapidRuins,
        ZombieZoom,
        MaracarMadness,
        NightmareMeander,
        MaracaMelee,
        CastleChaos,
        VolcanoVelocity,
        RangerRush,
        TokyoTakeover,
        FatalFinale
    }
}
